//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.24 at 07:29:17 PM EDT 
//


package org.immregistries.dqa.hub.report.vaccine;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ageCategoryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ageCategoryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ageCategoryId" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="displayOrder" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="minAge" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="maxAge" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ageCategoryType", propOrder = {
    "ageCategoryId",
    "label",
    "displayOrder",
    "minAge",
    "maxAge"
})
public class AgeCategoryType {

    protected byte ageCategoryId;
    @XmlElement(required = true)
    protected String label;
    protected byte displayOrder;
    protected byte minAge;
    protected short maxAge;

    /**
     * Gets the value of the ageCategoryId property.
     * 
     */
    public byte getAgeCategoryId() {
        return ageCategoryId;
    }

    /**
     * Sets the value of the ageCategoryId property.
     * 
     */
    public void setAgeCategoryId(byte value) {
        this.ageCategoryId = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the displayOrder property.
     * 
     */
    public byte getDisplayOrder() {
        return displayOrder;
    }

    /**
     * Sets the value of the displayOrder property.
     * 
     */
    public void setDisplayOrder(byte value) {
        this.displayOrder = value;
    }

    /**
     * Gets the value of the minAge property.
     * 
     */
    public byte getMinAge() {
        return minAge;
    }

    /**
     * Sets the value of the minAge property.
     * 
     */
    public void setMinAge(byte value) {
        this.minAge = value;
    }

    /**
     * Gets the value of the maxAge property.
     * 
     */
    public short getMaxAge() {
        return maxAge;
    }

    /**
     * Sets the value of the maxAge property.
     * 
     */
    public void setMaxAge(short value) {
        this.maxAge = value;
    }

}
