//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.24 at 07:29:17 PM EDT 
//


package org.immregistries.dqa.hub.report.vaccine;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for expectationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="expectationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ageCategoryId" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="includeStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "expectationType", propOrder = {
    "ageCategoryId",
    "includeStatus"
})
public class ExpectationType {

    protected byte ageCategoryId;
    @XmlElement(required = true)
    protected String includeStatus;

    /**
     * Gets the value of the ageCategoryId property.
     * 
     */
    public byte getAgeCategoryId() {
        return ageCategoryId;
    }

    /**
     * Sets the value of the ageCategoryId property.
     * 
     */
    public void setAgeCategoryId(byte value) {
        this.ageCategoryId = value;
    }

    /**
     * Gets the value of the includeStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncludeStatus() {
        return includeStatus;
    }

    /**
     * Sets the value of the includeStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncludeStatus(String value) {
        this.includeStatus = value;
    }

}
