//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.24 at 07:29:17 PM EDT 
//


package org.immregistries.dqa.hub.report.vaccine;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for vaccineCodesReportType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="vaccineCodesReportType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ageCategory" type="{}ageCategoryType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="vaccineGroup" type="{}vaccineGroupType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vaccineCodesReportType", propOrder = {
    "ageCategory",
    "vaccineGroup"
})
public class VaccineCodesReportType {

    protected List<AgeCategoryType> ageCategory;
    protected List<VaccineGroupType> vaccineGroup;

    /**
     * Gets the value of the ageCategory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ageCategory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgeCategory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AgeCategoryType }
     * 
     * 
     */
    public List<AgeCategoryType> getAgeCategory() {
        if (ageCategory == null) {
            ageCategory = new ArrayList<AgeCategoryType>();
        }
        return this.ageCategory;
    }

    /**
     * Gets the value of the vaccineGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vaccineGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVaccineGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VaccineGroupType }
     * 
     * 
     */
    public List<VaccineGroupType> getVaccineGroup() {
        if (vaccineGroup == null) {
            vaccineGroup = new ArrayList<VaccineGroupType>();
        }
        return this.vaccineGroup;
    }

}
