//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.24 at 07:29:17 PM EDT 
//


package org.immregistries.dqa.hub.report.vaccine;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for vaccineGroupType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="vaccineGroupType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vaccineGroupId" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="displayOrder" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="expectedThreshold" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cvx" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="expectation" type="{}expectationType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vaccineGroupType", propOrder = {
    "vaccineGroupId",
    "label",
    "displayOrder",
    "expectedThreshold",
    "cvx",
    "expectation"
})
public class VaccineGroupType {

    protected short vaccineGroupId;
    @XmlElement(required = true)
    protected String label;
    protected short displayOrder;
    @XmlElement(required = true)
    protected String expectedThreshold;
    @XmlElement(required = true)
    protected String cvx;
    protected List<ExpectationType> expectation;

    /**
     * Gets the value of the vaccineGroupId property.
     * 
     */
    public short getVaccineGroupId() {
        return vaccineGroupId;
    }

    /**
     * Sets the value of the vaccineGroupId property.
     * 
     */
    public void setVaccineGroupId(short value) {
        this.vaccineGroupId = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the displayOrder property.
     * 
     */
    public short getDisplayOrder() {
        return displayOrder;
    }

    /**
     * Sets the value of the displayOrder property.
     * 
     */
    public void setDisplayOrder(short value) {
        this.displayOrder = value;
    }

    /**
     * Gets the value of the expectedThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpectedThreshold() {
        return expectedThreshold;
    }

    /**
     * Sets the value of the expectedThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpectedThreshold(String value) {
        this.expectedThreshold = value;
    }

    /**
     * Gets the value of the cvx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCvx() {
        return cvx;
    }

    /**
     * Sets the value of the cvx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCvx(String value) {
        this.cvx = value;
    }

    /**
     * Gets the value of the expectation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the expectation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExpectation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExpectationType }
     * 
     * 
     */
    public List<ExpectationType> getExpectation() {
        if (expectation == null) {
            expectation = new ArrayList<ExpectationType>();
        }
        return this.expectation;
    }

}
